version: '3.4'

services:
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
        
  helloworldservice:
    image: ${DOCKER_REGISTRY-}helloworldservice
    build:
      context: .
      dockerfile: HelloWorldService/Dockerfile
    restart: always

  mymicroservice:
    image: ${DOCKER_REGISTRY-}mymicroservice
    build:
      context: .
      dockerfile: MyMicroservice/Dockerfile
    depends_on:
      - helloworldservice
      - rabbitmq
    restart: always

